### ISSUE TITLE
Need help translating ?

### ISSUE THREAD

**Issue by DBChoco** [Jessewb786/Silaty#14]
Assalamou Alaykoum wa Rahmatou Lahi wa Baraketu brother/sister.

I was wondering if you needed help translating the app to other languages, I can do French and Spanish if you want.
Jazzaka Lahu khairan for the app as well.

**Comment by AXeL-dev** [comment]
wa alaykoumo salamo wa rahmato lahi wa barakatu,

Yes sure any help is welcome, you can simply fill the french translations array in this [file](https://github.com/LinuxForGeeks/Silaty/blob/755c3f484aa65ff577794ffc7b98e1dcd61dfdb3/translate.py#L134), then add the language to the settings [here](https://github.com/LinuxForGeeks/Silaty/blob/755c3f484aa65ff577794ffc7b98e1dcd61dfdb3/options.py#L99).

Once you're good to go, create a pull request with the changes you did. Good luck!

**Comment by DBChoco** [comment]
Here it is, I hope it's to your liking!
https://github.com/LinuxForGeeks/Silaty/pull/4

**Comment by AXeL-dev** [comment]
You did a great job! :tada:  Thanks again.

**Note:** i'll push a pull request to the main repo (this one) later, so it can be integrated here too.

**Comment by DBChoco** [comment]
It's my pleasure akhi! Have a nice end of Ramadan!
