### ISSUE TITLE
Settings won't open

### ISSUE THREAD

**Issue by 7786** [Jessewb786/Silaty#2]
Trying to open Settings from the indicator brings up the following errors:

'Traceback (most recent call last):
  File "/usr/local/bin/silaty-indicator", line 190, in show_settings
    self.silaty.set_layout()
  File "/usr/share/silaty/silaty.py", line 72, in set_layout
    self.set_options()
  File "/usr/share/silaty/silaty.py", line 210, in set_options
    active_text = adhans.index(defaultadhan)
ValueError: 'Nasir Al-Qatami' is not in list'

'(silaty-indicator:2471): Gtk-WARNING **: Child name 'options' not found in GtkStack
Traceback (most recent call last):
  File "/usr/share/silaty/sidebar.py", line 40, in activate_button
    index = self.stackchildnames.index(visiblechild)
ValueError: None is not in list'

**Comment by bilelmoussaoui** [comment]
I had the same issue when i change the location :/ the best way is to add autolocation too! I tried to remove the configuration file but it's dosent change anything?

**Comment by Jessewb786** [comment]
A temporary fix for this is to do

rm ~/.silaty

Then start the app again. This will restore the default settings.

**Comment by 7786** [comment]
Jazakallah for your reply. After doing, it seems to have reset the default settings back to Makkah. But unfortunately clicking on Settings still doesn't open up the Settings window, although it does put a gear icon in the dock.

http://i.imgur.com/ZBVCHEB.png

**Comment by bilelmoussaoui** [comment]
I know that i have to open a new issue. But could you please make the indicator icon white as the standards icons in eOS?
